# Generated by Django 3.2.25 on 2024-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/logos", verbose_name="foto"
            ),
        ),
    ]
